apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "skf-ingress-controller"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 132.185.0.0/16,81.187.149.40,212.58.232.176/28
spec:
  tls:
  - hosts:
    - skf-k8s.vuln-tracker.dev
    secretName: skf-k8s.vuln-tracker.dev
  rules:
  - host: skf-k8s.vuln-tracker.dev
    http:
     paths:
     - backend:
         serviceName: skf-flask-front
         servicePort: 8788
       path: /  
     - backend:
         serviceName: skf-flask-back
         servicePort: 8888
       path: /api
     - backend:
         serviceName: skf-flask-back
         servicePort: 8888
       path: /swaggerui
